server:
  port: 8082

spring:
  application:
    name: demo-client
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        enabled: ${NACOS_ENABLED:false}
      config:
        server-addr: ${NACOS_ADDR:localhost:8848}
        enabled: ${NACOS_ENABLED:false}
        file-extension: yml

# Elasticsearch
elasticsearch:
  host: ${ES_HOST:localhost}
  port: ${ES_PORT:9200}
  scheme: ${ES_SCHEME:http}
  username: ${ES_USERNAME:}
  password: ${ES_PASSWORD:}

logging:
  level:
    com.example: debug
